### ISSUE TITLE
Codepen demo fails

### ISSUE THREAD

**Issue by nicholas-c** [lucagez/tattica#6]
![image](https://user-images.githubusercontent.com/6815423/53739577-00b85480-3e8a-11e9-9bc6-937dcbd281b9.png)

Firefox 65.0.1 on Mac

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/connection

navigator.connection is only in Chrome it seems and is a draft spec.

**Comment by lucagez** [comment]
Hi, yes you are totally right! I forgot to check the browser compatibility table for navigator.
I am going to enable it only for Chrome

**Comment by lucagez** [comment]
Now adaptive-serving will check the avaiability of navigator.connection before starting.
If navigator.connection is not present in browser, a normal loading queue using default `data-src` will be used.

**Comment by lucagez** [comment]
Updated `readme.md` and `codepen demo` adding a warning: only Chrome supports adaptive serving.

**Comment by lucagez** [comment]
Updated npm package with the bug-fix
